version: '3.7'

services:
  python_app:
    build: ./app
    ports:
      - "5001:5000"

  prometheus:
    image: prom/prometheus:v2.30.3
    volumes:
      - ./prometheus-config:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:8.3.3
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage:
