[package]
name = "codeduplication"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html



[dependencies]
tokenizers = "0.11.3"
ndarray = "0.15.4"


[build-dependencies]
bindgen = "0.60.1"