lr: 0.001
horizon: 96
lookback: 720
ne_blocks: 2
nd_blocks: 2
hidden_size: 1024
dropout_level: 0.5
covariates_size: 0
temporal_decoder_hidden_size: 64
decoder_output_size:  ${mul:8,${.horizon}}
static_covariates_size: 1
max_epochs: 1000
feature_projection_output_size: 32
feature_projection_hidden_size: 32
train_size: 0.8
train_batch_size: 64
test_batch_size: 64